# Uncomment the next line to define a global platform for your project
# platform :ios, "9.0"

target "VKFileBrowserDemo" do
  # Comment the next line if you"re not using Swift and don"t want to use dynamic frameworks
  use_frameworks!

  # Pods for VKFileBrowserDemo

# pod "SSZipArchive"
 pod "CocoaLumberjack/Swift", "~> 3.0"
 pod "GCDWebServer", "~> 3.3"
 pod "GCDWebServer/WebUploader", "~> 3.3"
 pod "GCDWebServer/WebDAV", "~> 3.3"
 pod "MJRefresh"
 pod "MWPhotoBrowser"
 pod "Alamofire"
 pod "MJExtension"
 pod "MBProgressHUD"
 pod "Highlightr"
 pod "SwiftyMarkdown"
 pod "SwipeCellKit"
 pod "MGSwipeTableCell"
 pod "Result"
# pod "RealmSwift"
# pod "Texture"
# pod "DZNEmptyDataSet"
# pod "IGListKit"
 pod "Moya"
# pod "SwiftyJSON"
 pod "ChameleonFramework/Swift", :git => "https://github.com/ViccAlexander/Chameleon.git"
# pod "PermissionScope"
# pod "FileKit"
 pod "SwiftyUserDefaults"
# pod "Hero"
# pod "Hedwig"
# pod "DeviceKit"
# pod "Charts"
# pod "ChartsRealm"
# pod "GDPerformanceView-Swift"
 pod "RxSwift"
 pod 'AMScrollingNavbar'
 pod "RxCocoa"
 pod 'RxDataSources', '~> 1.0'
# pod "Timepiece"
# pod "CryptoSwift"
# pod "FSCalendar"
# pod "TextFieldEffects"
# pod "FontAwesomeKit"
# pod "CoreDragon"
# pod "ReSwift"
# pod "TransitionTreasury"
# pod "ElasticTransition"
 pod "VBFPopFlatButton"
 pod "InAppSettingsKit"
 pod "SCLAlertView"
 
# pod "Quick"
# pod "Nimble"
 
  target "VKFileBrowserDemoTests" do
    inherit! :search_paths
    # Pods for testing
  end

  target "VKFileBrowserDemoUITests" do
    inherit! :search_paths
    # Pods for testing
  end

end
