# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VKFileBrowserDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VKFileBrowserDemo

# pod "SSZipArchive"
 pod "CocoaLumberjack/Swift", "~> 3.0"
 pod "GCDWebServer", "~> 3.3"
 pod "GCDWebServer/WebUploader", "~> 3.3"
 pod "GCDWebServer/WebDAV", "~> 3.3"
 pod "MJRefresh"
 pod "MWPhotoBrowser"
 pod "Alamofire"
 pod "MJExtension"
 pod "MBProgressHUD"
 pod "Highlightr"
 pod "SwiftyMarkdown"
 pod "SwipeCellKit"
 pod "Result"
 
  target 'VKFileBrowserDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VKFileBrowserDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
