# Uncomment the next line to define a global platform for your project
platform :ios, "10.0"

target "VKFileBrowserDemo" do
  # Comment the next line if you"re not using Swift and don"t want to use dynamic frameworks
  use_frameworks!

  # Pods for VKFileBrowserDemo

# pod "SSZipArchive"
 pod "CocoaLumberjack/Swift", "~> 3.0"
 pod "GCDWebServer", "~> 3.3"
 pod "GCDWebServer/WebUploader", "~> 3.3"
 pod "GCDWebServer/WebDAV", "~> 3.3"
 pod "MJRefresh"
 pod "MWPhotoBrowser"
 pod "Alamofire"
 pod "MJExtension"
 pod "SVProgressHUD"
 pod "Highlightr"
 pod "SwiftyMarkdown"
 pod "MGSwipeTableCell"
 pod "Result"
 pod 'ReachabilitySwift'
 pod "RealmSwift"
 pod "RxRealm"
 pod "RxRealmDataSources"
# pod "Texture"
# pod "DZNEmptyDataSet"
# pod "IGListKit"
 pod "Moya"
# pod "SwiftyJSON"
 pod "ChameleonFramework/Swift", :git => "https://github.com/ViccAlexander/Chameleon.git"
# pod "PermissionScope"
# pod "FileKit"
 pod "SwiftyUserDefaults"
 pod "Hero"
 pod "ObjectMapper"
# pod "Hedwig"
# pod "DeviceKit"
# pod "Charts"
# pod "ChartsRealm"
# pod "GDPerformanceView-Swift"
 pod "RxSwift"
 pod 'AMScrollingNavbar'
 pod "RxCocoa"
 pod 'RxDataSources', '~> 1.0'
# pod "Timepiece"
# pod "CryptoSwift"
# pod "FSCalendar"
# pod "TextFieldEffects"
# pod "FontAwesomeKit"
# pod "CoreDragon"
# pod "ReSwift"
# pod "TransitionTreasury"
# pod "ElasticTransition"
 pod "VBFPopFlatButton"
 pod "InAppSettingsKit"
 pod "SCLAlertView"
 pod 'SnapKit'
 pod 'Validator'
# pod "Quick"
# pod "Nimble"

end
target "HtmlDebugger" do
 use_frameworks!
 pod "MGSwipeTableCell"
 pod "VBFPopFlatButton"
 pod "RealmSwift"
 pod "RxRealm"
 pod "Highlightr"
 pod "RxRealmDataSources"
 pod "RxSwift"
 pod 'AMScrollingNavbar'
 pod "RxCocoa"
 pod 'RxDataSources', '~> 1.0'
 pod 'SnapKit'
 pod "SwiftyUserDefaults"
 pod "SVProgressHUD"
 pod "ChameleonFramework/Swift", :git => "https://github.com/ViccAlexander/Chameleon.git"
 pod 'SwiftSoup'
end



