//
// Constatnt.swift
// Highlight
//
// This file is automatically generated.
// DO NOT MODIFY THIS FILE MANUALLY
//
import UIKit
import ChameleonFramework


public let SCREEN_WIDTH = UIScreen.main.nativeBounds.size.width
public let SCREEN_HEIGHT = UIScreen.main.nativeBounds.size.height

public let IS_PAD = UIDevice.current.userInterfaceIdiom == .pad
public let IS_PHONE = UIDevice.current.userInterfaceIdiom == .phone

public let CGRectZero = CGRect()

public func LocalizedString(_ key:String) -> String {
    return NSLocalizedString(key, comment: key)
}


let appDelegate = UIApplication.shared.delegate as! AppDelegate

public let documentDir : String = NSSearchPathForDirectoriesInDomains(.documentDirectory, .userDomainMask, true).last!

public func debugStr(_ item:Any?) {
    guard let item = item else {
        return
    }
    print("debugStr:\(item)")
}
